version: "2"

services:
    web-service:
        container_name: wh2o-web-container
        image: wh2o-web-image
        build: 
            context: .
            dockerfile: ./docker/wh2o-web/Dockerfile
        ports:
            - "8080:8080"
    api-service:
        container_name: wh2o-api-container
        image: wh2o-api-image
        build: 
            context: .
            dockerfile: ./docker/wh2o-api/Dockerfile
        environment: 
            HOST: 0.0.0.0
            PORT: 3030
        ports:
            - "3030:3030"
