version: 3.7
services:
  wh2o-web:
    container_name: wh2o-web
    build:
      context: .
      dockerfile: ./.docker/wh2o-web.dockerfile
    ports:
      - 8080:8080
    networks:
      - wh2o-network
    depends_on: 
      - server
    volumes: 
       - ./wh2o-web/node_modules:/var/www/node_modules
  wh2o-api:
    container_name: wh2o-api
    build:
      args: 
        user: wh2o
        uid: 1234
      context: .
      dockerfile: ./.docker/wh2o-api.dockerfile
    ports:
      - 3333:3333
    networks:
      - wh2o-network
    depends_on:
      - wh2o-db
    volumes: 
       - ./wh2o-api/node_modules:/var/www/node_modules
  wh2o-db:
    container_name: wh2o-db
    image: mdillon/postgis
    environment:
      - POSTGRES_DB=wh2o
      - POSTGRES_USER=wh2o
      - POSTGRES_PASSWORD=wh2o
    ports:
      - 55432:5432
    networks:
      - wh2o-network
networks:
  wh2o-network:
    driver: bridge