version: '3.7'
services:
  wh2o-web:
    container_name: web-container
    build:
      context: .
      dockerfile: ./.docker/wh2o-web.dockerfile
    ports:
      - 8080:8080
    networks:
      - default-network
    depends_on: 
      - wh2o-api
  wh2o-api:
    container_name: api-container
    build:
      context: .
      dockerfile: ./.docker/wh2o-api.dockerfile
    ports:
      - 8000:8000
    networks:
      - default-network
    depends_on:
      - wh2o-db
  wh2o-db:
    container_name: db-container
    image: mdillon/postgis
    environment:
      - POSTGRES_DB=wh2o
      - POSTGRES_USER=wh2o
      - POSTGRES_PASSWORD=wh2o
    ports:
      - 55432:5432
    networks:
      - default-network
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  default-network:
    driver: bridge
volumes:
  pgdata:
    external: true