version: '3.7'
services:
  wh2o-admin:
    container_name: admin-container
    build:
      context: .
      dockerfile: ./docker/wh2o-admin.dockerfile
    ports:
      - 8080:8080
    depends_on: 
      - wh2o-api
  wh2o-api:
    container_name: api-container
    build:
      context: .
      dockerfile: ./docker/wh2o-api.dockerfile
    ports:
      - 3000:3000
    depends_on:
      - wh2o-db
    command: ["./wait-for-postgres.sh", "node", "dist/index.js"]

  wh2o-db:
      container_name: db-container
      image: postgres:10.4
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: wh2o
        POSTGRES_PASSWORD: wh2o
        POSTGRES_DB: db