version: "2"

services:
    web-service:
        container_name: wh2o-web-container
        image: wh2o-web-image
        build: 
            context: .
            dockerfile: ./docker/wh2o-web/Dockerfile
        ports:
            - "8080:8080"
        depends_on: 
            - api-service
        networks:
            - default
    api-service:
        container_name: wh2o-api-container
        image: wh2o-api-image
        build: 
            context: .
            dockerfile: ./docker/wh2o-api/Dockerfile
        environment: 
            HOST: 0.0.0.0
            PORT: 3030
        ports:
            - "3030:3030"
        depends_on: 
            - dbserver
        networks:
            - default
    dbserver:
        container_name: wh2o-mysql-container
        image: wh2o-mysql-image
        build:
            context: .
            dockerfile: ./docker/wh2o-mysql/Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: wh2o
        ports:
            - "3308:3306"
        networks:
            - default